---
- name: Check if cargo is installed
  ansible.builtin.command: which cargo
  register: cargo_exists
  ignore_errors: true

- name: Download cargo Installer
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
- name: Install rust/cargo
  when: cargo_exists is failed
  ansible.builtin.shell: /tmp/sh.rustup.rs -y
- name: Upgrade Rust
  become: true
  ansible.builtin.command: rustup update
