---
- name: Run tasks on localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "Hello, localhost!"
- name: Fetch hostname
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Print hostname
      ansible.builtin.debug:
        var: ansible_hostname
- name: Update
  hosts: localhost
  become: true
  roles:
    - upgrade
- name: Golang
  hosts: localhost
  roles:
    - role: golang
      tags:
        - golang
- name: Copyq
  hosts: localhost
  become: true
  roles:
    - role: copyq
      tags:
        - copyq
- name: Kitty
  hosts: localhost
  roles:
    - role: kitty
      tags:
        - kitty

- name: Node
  hosts: localhost
  roles:
    - role: node
      tags:
        - node
- name: Applications
  hosts: localhost
  roles:
    - rust
    - firebase
    - fish
    - nvim
    - role: glow
      tags:
        - glow
- name: Properties
  hosts: localhost
  become: false
  roles:
    - upgradeproperties

- name: Bash customization
  hosts: localhost
  roles:
    - bashcustomization
  tags:
    - bash
