---
- name: Run tasks on localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "Hello, localhost!"
- name: Fetch hostname
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Print hostname
      ansible.builtin.debug:
        var: ansible_hostname
- name: Ask for sudo
  hosts: localhost
  become: true
  become_method: ansible.builtin.sudo
  vars_prompt:
    - name: ansible_become_password
      prompt: "Enter your password for sudo:"
      private: true
- name: Update 
  hosts: localhost
  become: true
  roles:
    - upgrade
- name: Applications
  hosts: localhost
  roles:
    - rust
    - golang
    - node
    - firebase
    - fish
    - nvim
- name: properties 
  hosts: localhost
  become: false
  roles:
    - upgradeproperties
