---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
- name: Cleanup
  ansible.builtin.apt:
    autoclean: yes
    autoremove: yes
- name: Upgrade packages
  apt:
    upgrade: dist
- name: Install 
  ansible.builtin.apt:
    name:
    - cowsay
    - python3
    - python3.10-venv
    - tar
    - jq
    - xclip
    - fzf
    # - xmllint
- name: Snaps 
  ansible.builtin.command: snap refresh
