---

- name: Install Node.js and npm
  apt:
    name: nodejs
    state: present
- name: Update npm
  ansible.builtin.command: npm install -g npm
  become: true
- name: Update npm
  ansible.builtin.command: npm install -g neovim
  become: true

- name: Is pnpm installed
  command: "which pnpm"
  register: command_output
  ignore_errors: true  # This ensures that the task doesn't fail even if the command is not found
- name: Install Pnpm
  when: "not 'pnpm' in command_output.stdout"
  command: npm install -g @pnpm/exe 
- name: Generate pnpm completion
  command: pnpm completion bash
  register: completion_output
  changed_when: false

- name: Save completion script to file
  copy:
    content: "{{ completion_output.stdout }}"
    dest: ~/.pnpm-completion.sh
    mode: '0644'
- name: Append completion lines to ~/.bashrc
  blockinfile:
    path: ~/.bashrc
    block: |
      if [ -f ~/.pnpm-completion.sh ]; then
          . ~/.pnpm-completion.sh
      fi

