---
- name: Fetch recent
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/stable/nvim.appimage 
    dest: ~/programs/nvim
    mode: '0755'
    force: 'yes'
- name: Check if PATH contains the path
  command: echo $PATH
  register: path_output
- name: Update PATH if the path is not present
  ansible.builtin.lineinfile:
    path: ~/.bashrc  # Path to the shell configuration file (e.g., ~/.bashrc)
    line: 'export PATH="$PATH:~/programs"'
    insertafter: EOF
    state: present
    create: yes
  when: "'~/programs' not in path_output.stdout"
- name: Update packer
  ansible.builtin.command: ~/programs/nvim --headless -c 'lua UpdatePacker()' -c 'q'
- name: Update mason
  ansible.builtin.command: ~/programs/nvim --headless -c 'MasonUpdate' -c 'q'

