---
- name: Fetch fzf
  ansible.builtin.command: git clone --depth 1 https://github.com/junegunn/fzf.git 
  ignore_errors: true
- name: Update fzf
  ansible.builtin.command:  git pull
  args:
    chdir: fzf
- name: Install fzf
  ansible.builtin.command: ./fzf/install --all
- name: Check if environment variable is defined and has the desired value
  set_fact:
      env_variable_defined: "{{'FZF_DEFAULT_OPTS' in lookup('env', 'HOST_ENV')}}"
      env_variable_value: "lookup('env', 'HOST_ENV')"
- name: Add line in bashrc if needed
  lineinfile:
      dest: "~/.bashrc"
      line: "export FZF_DEFAULT_OPTS=\"{{ fzf_options }}\""
      insertafter: EOF
      state: present
      create: yes
  when: not env_variable_defined 
- name: Add or replace line in bashrc if needed
  lineinfile:
      dest: "~/.bashrc"
      line: "export FZF_DEFAULT_OPTS=\"{{ fzf_options }}\""
      regexp: '^export FZF_DEFAULT_OPTS='
  when: env_variable_defined and env_variable_value !=  fzf_options 

- name: Check if fzf command set
  set_fact:
      fzf_command_defined: "{{'FZF_DEFAULT_COMMAND' in lookup('env', 'HOST_ENV')}}"
- name: Add line in bashrc if needed
  lineinfile:
      dest: "~/.bashrc"
      line: "export FZF_DEFAULT_COMMAND=\"{{ fzf_command }}\""
      insertafter: EOF
      state: present
      create: yes
  when: not fzf_command_defined 

